name: Build NK Music Box APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: |
          PROJ_DIR=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \;)
          echo "Flutter projesi klasörü: $PROJ_DIR"
          cd $PROJ_DIR
          flutter pub get

      - name: Build APK
        run: |
          PROJ_DIR=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \;)
          cd $PROJ_DIR
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nk-Music-Box-Release-APK
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
